### ISSUE TITLE
This seems to be failing with the latest version of Rakudo

### ISSUE THREAD

**Issue by JJ** [perl6-community-modules/uri#39]
As shown in [this Travis log](https://travis-ci.org/perl6/doc/jobs/481277865)

**Comment by ufobat** [comment]
Thats not because of rakudo or uri.
It seems that there is a TAP::Harness in version 0.0.6 on CPAN, uploaded last year's christmas day:

see `zef search TAP::Harness`

in this version there is a bug that executes all files in t/ that end with the letter `t`. 
You can see the bug here: https://modules.perl6.org/dist/TAP:cpan:LEONT/bin/prove6#L11

no clue what happend? I guess @leont can help.

**Comment by jonathanstowe** [comment]
Ha, I thought that was a _feature_ and patched around it ;-)

**Comment by Leont** [comment]
Fixed in 0.0.7

**Comment by Leont** [comment]
(This can be closed)
